export const SAMPLE_GALLERY = [
  {
    id: 's1',
    image_url: '/images/gallery/one.jpg',
    title_en: 'Basement Waterproofing',
    title_ne: 'बेसमेन्ट वाटरप्रूफिङ',
    description_en: 'Full excavation, membrane application, and sealing for a below-grade basement wall.',
    description_ne: 'भूमिगत बेसमेन्ट पर्खालको पूर्ण उत्खनन, झिल्ली प्रयोग, र सिलिङ।',
    project_type: 'Basement',
    location: 'Lalitpur',
    featured: true,
  },
  {
    id: 's2',
    image_url: '/images/gallery/two.jpg',
    title_en: 'Roof Terrace Sealing',
    title_ne: 'छत सिलिङ',
    description_en: 'Liquid membrane applied across a 200 sq.m roof terrace.',
    description_ne: '२०० वर्ग मिटर छत टेरेसमा तरल झिल्ली लागू गरिएको।',
    project_type: 'Roof',
    location: 'Kathmandu',
    featured: false,
  },
  {
    id: 's3',
    image_url: '/images/gallery/four.jpg',
    title_en: 'Foundation Injection',
    title_ne: 'जग इन्जेक्सन',
    description_en: 'Crack injection and structural waterproofing for commercial foundation.',
    description_ne: 'व्यावसायिक भवनको जगमा दरार इन्जेक्सन र संरचनात्मक वाटरप्रूफिङ।',
    project_type: 'Foundation',
    location: 'Bhaktapur',
    featured: true,
  },
  {
    id: 's4',
    image_url: '/images/gallery/five.webp',
    title_en: 'Bathroom Membrane',
    title_ne: 'बाथरूम झिल्ली',
    description_en: 'Full bathroom floor and wall waterproofing prior to tiling.',
    description_ne: 'टाइलिङ अघि पूर्ण बाथरूम भुइँ र पर्खाल वाटरप्रूफिङ।',
    project_type: 'Bathroom',
    location: 'Kathmandu',
    featured: false,
  },
  {
    id: 's5',
    image_url: '/images/gallery/six.jpg',
    title_en: 'Exterior Wall Treatment',
    title_ne: 'बाहिरी पर्खाल उपचार',
    description_en: 'Weather-proofing and coating applied on monsoon-exposed exterior wall.',
    description_ne: 'मनसुनमा खुला रहेको बाहिरी पर्खालमा वेदर-प्रूफिङ कोटिङ।',
    project_type: 'Wall',
    location: 'Pokhara',
    featured: false,
  },
  {
    id: 's6',
    image_url: '/images/gallery/seven.jpg',
    title_en: 'Terrace Drainage Fix',
    title_ne: 'टेरेस ड्रेनेज मर्मत',
    description_en: 'Repaired and sealed a leaking roof terrace for a residential building.',
    description_ne: 'आवासीय भवनको चुहिने छत टेरेस मर्मत र सिल गरिएको।',
    project_type: 'Terrace',
    location: 'Kathmandu',
    featured: false,
  },
  {
    id: 's7',
    image_url: '/images/gallery/eight.jpg',
    title_en: 'Commercial Basement',
    title_ne: 'व्यावसायिक बेसमेन्ट',
    description_en: 'Large-scale commercial basement sealing and drainage system.',
    description_ne: 'ठूलो परिमाणको व्यावसायिक बेसमेन्ट सिलिङ र ड्रेनेज प्रणाली।',
    project_type: 'Basement',
    location: 'Kathmandu',
    featured: true,
  },
  {
    id: 's8',
    image_url: '/images/gallery/nine.jpeg',
    title_en: 'Roof Leak Repair',
    title_ne: 'छत चुहावट मर्मत',
    description_en: 'Identified and sealed multiple roof leak points on a two-story home.',
    description_ne: 'दुई तल्ले घरमा धेरै छत चुहावट बिन्दुहरू पहिचान र सिल गरिएको।',
    project_type: 'Roof',
    location: 'Lalitpur',
    featured: false,
  },
  {
    id: 's9',
    image_url: '/images/gallery/ten.jpeg',
    title_en: 'Wall Protection',
    title_ne: 'पर्खाल सुरक्षा',
    description_en: 'Full exterior wall waterproof coating to prevent seepage.',
    description_ne: 'सिपेज रोक्न बाहिरी पर्खालमा पूर्ण वाटरप्रूफ कोटिङ।',
    project_type: 'Wall',
    location: 'Bhaktapur',
    featured: false,
  },
  {
    id: 's10',
    image_url: '/images/gallery/eleven.jpeg',
    title_en: 'Terrace Restoration',
    title_ne: 'टेरेस पुनर्स्थापना',
    description_en: 'Restored and waterproofed an aging terrace surface.',
    description_ne: 'पुरानो टेरेस सतहको पुनर्स्थापना र वाटरप्रूफिङ।',
    project_type: 'Terrace',
    location: 'Kathmandu',
    featured: false,
  },
  {
    id: 's11',
    image_url: '/images/gallery/service.jpg',
    title_en: 'On-site Inspection',
    title_ne: 'साइट निरीक्षण',
    description_en: 'Our certified team performing an on-site inspection and consultation.',
    description_ne: 'हाम्रो प्रमाणित टोलीद्वारा साइट निरीक्षण र परामर्श।',
    project_type: 'Other',
    location: 'Kathmandu',
    featured: false,
  },
];
